// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coolantRed = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_coolantRed);
    lv_obj_set_width(ui_coolantRed, 240);
    lv_obj_set_height(ui_coolantRed, 100);
    lv_obj_clear_flag(ui_coolantRed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_coolantRed, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_coolantRed, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_oilRed = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_oilRed);
    lv_obj_set_width(ui_oilRed, 240);
    lv_obj_set_height(ui_oilRed, 100);
    lv_obj_set_x(ui_oilRed, 0);
    lv_obj_set_y(ui_oilRed, 85);
    lv_obj_clear_flag(ui_oilRed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_oilRed, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_oilRed, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_intakeRed = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_intakeRed);
    lv_obj_set_width(ui_intakeRed, 240);
    lv_obj_set_height(ui_intakeRed, 110);
    lv_obj_set_x(ui_intakeRed, 0);
    lv_obj_set_y(ui_intakeRed, 170);
    lv_obj_clear_flag(ui_intakeRed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_intakeRed, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_intakeRed, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_coolantLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_coolantLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_coolantLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_coolantLabel, 45);
    lv_obj_set_y(ui_coolantLabel, 20);
    lv_label_set_text(ui_coolantLabel, "Coolant temp:");
    lv_obj_set_style_text_color(ui_coolantLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_coolantLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_coolantLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_coolantLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_coolantLabel, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_coolantTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_coolantTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_coolantTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_coolantTemp, 45);
    lv_obj_set_y(ui_coolantTemp, 40);
    lv_label_set_text(ui_coolantTemp, "80 °C");
    lv_obj_set_style_text_color(ui_coolantTemp, lv_color_hex(0x00F7FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_coolantTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_coolantTemp, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_coolantTemp, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_coolantTemp, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_coolantTemp, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_coolantTemp, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_color(ui_coolantTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_coolantTemp, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_oilLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_oilLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oilLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_oilLabel, 45);
    lv_obj_set_y(ui_oilLabel, 105);
    lv_label_set_text(ui_oilLabel, "Oil temp:");
    lv_obj_set_style_text_color(ui_oilLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oilLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oilLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_oilLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_oilLabel, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_oilTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_oilTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oilTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_oilTemp, 45);
    lv_obj_set_y(ui_oilTemp, 125);
    lv_label_set_text(ui_oilTemp, "80");
    lv_obj_set_style_text_color(ui_oilTemp, lv_color_hex(0x00F7FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oilTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oilTemp, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_oilTemp, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_oilTemp, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_color(ui_oilTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_oilTemp, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_intakeLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_intakeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_intakeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_intakeLabel, 45);
    lv_obj_set_y(ui_intakeLabel, 190);
    lv_label_set_text(ui_intakeLabel, "Intake temp:");
    lv_obj_set_style_text_color(ui_intakeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_intakeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_intakeLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_intakeLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_intakeLabel, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_intakeTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_intakeTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_intakeTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_intakeTemp, 45);
    lv_obj_set_y(ui_intakeTemp, 210);
    lv_label_set_text(ui_intakeTemp, "80");
    lv_obj_set_style_text_color(ui_intakeTemp, lv_color_hex(0x00F7FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_intakeTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_intakeTemp, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_intakeTemp, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_intakeTemp, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_color(ui_intakeTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_intakeTemp, 255, LV_PART_MAIN | LV_STATE_USER_3);

}
