// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gearBackground = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_gearBackground);
    lv_obj_set_width(ui_gearBackground, 240);
    lv_obj_set_height(ui_gearBackground, 280);
    lv_obj_set_align(ui_gearBackground, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_gearBackground, LV_STATE_USER_2);       /// States
    lv_obj_clear_flag(ui_gearBackground, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_gearBackground, lv_color_hex(0x084900), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_gearBackground, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_gearBackground, lv_color_hex(0x754C00), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_gearBackground, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_gearBackground, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_gearBackground, 255, LV_PART_MAIN | LV_STATE_USER_3);

    lv_obj_set_style_bg_color(ui_gearBackground, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_gearBackground, 255, LV_PART_SCROLLBAR | LV_STATE_USER_2);

    ui_gearDisp = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_gearDisp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gearDisp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gearDisp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gearDisp, "N");
    lv_obj_set_style_text_color(ui_gearDisp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gearDisp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gearDisp, &ui_font_Signal_200_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gearDisp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_border_opa(ui_gearDisp, 255, LV_PART_MAIN | LV_STATE_USER_2);

}
