// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Dash V1

#include "../ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_accelX = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_accelX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_accelX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_accelX, 0);
    lv_obj_set_y(ui_accelX, 10);
    lv_obj_set_align(ui_accelX, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_accelX, "X:");
    lv_obj_set_style_text_color(ui_accelX, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_accelX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_accelX, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_accelX, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_accelX, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_accelY = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_accelY, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_accelY, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_accelY, 0);
    lv_obj_set_y(ui_accelY, 55);
    lv_obj_set_align(ui_accelY, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_accelY, "Y:");
    lv_obj_set_style_text_color(ui_accelY, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_accelY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_accelY, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_accelY, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_accelY, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_circle1 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_circle1);
    lv_obj_set_width(ui_circle1, 160);
    lv_obj_set_height(ui_circle1, 160);
    lv_obj_set_x(ui_circle1, 0);
    lv_obj_set_y(ui_circle1, 110);
    lv_obj_set_align(ui_circle1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_circle1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_circle1, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_circle1, lv_color_hex(0x271B03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_circle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_accelPointer = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_accelPointer);
    lv_obj_set_width(ui_accelPointer, 20);
    lv_obj_set_height(ui_accelPointer, 20);
    lv_obj_set_x(ui_accelPointer, 0);
    lv_obj_set_y(ui_accelPointer, 180);
    lv_obj_set_align(ui_accelPointer, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_accelPointer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_accelPointer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_accelPointer, lv_color_hex(0xCE9000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_accelPointer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


}
