// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_boostBar = lv_bar_create(ui_Screen2);
    lv_bar_set_range(ui_boostBar, 0, 1500);
    lv_bar_set_value(ui_boostBar, 200, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_boostBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_boostBar, 240);
    lv_obj_set_height(ui_boostBar, 50);
    lv_obj_set_x(ui_boostBar, 0);
    lv_obj_set_y(ui_boostBar, 190);
    lv_obj_set_style_radius(ui_boostBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_boostBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_boostBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_boostBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_boostBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_boostBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_boostLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_boostLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_boostLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_boostLabel, 0);
    lv_obj_set_y(ui_boostLabel, 25);
    lv_obj_set_align(ui_boostLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_boostLabel, "Boost:");
    lv_obj_set_style_text_color(ui_boostLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_boostLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_boostLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_boostLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_boostLabel, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_boost = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_boost, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_boost, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_boost, 0);
    lv_obj_set_y(ui_boost, 90);
    lv_obj_set_align(ui_boost, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_boost, "0.4");
    lv_obj_set_style_text_color(ui_boost, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_boost, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_boost, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_boost, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_boost, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_boost, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_boost, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_color(ui_boost, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_boost, 255, LV_PART_MAIN | LV_STATE_USER_3);

}
