// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Dash V1

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmLabel = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_rpmLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmLabel, 0);
    lv_obj_set_y(ui_rpmLabel, 30);
    lv_obj_set_align(ui_rpmLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_rpmLabel, "RPM:");
    lv_obj_set_style_text_color(ui_rpmLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpmLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpmLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_rpmLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_rpmLabel, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_rpmArc = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_rpmArc, 200);
    lv_obj_set_height(ui_rpmArc, 190);
    lv_obj_set_x(ui_rpmArc, 0);
    lv_obj_set_y(ui_rpmArc, 90);
    lv_obj_set_align(ui_rpmArc, LV_ALIGN_TOP_MID);
    lv_arc_set_range(ui_rpmArc, 0, 8000);
    lv_arc_set_value(ui_rpmArc, 2000);
    lv_obj_set_style_arc_color(ui_rpmArc, lv_color_hex(0x291E00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_rpmArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_rpmArc, lv_color_hex(0x9A7000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_rpmArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_rpmArc, lv_color_hex(0x9A7000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rpmArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rpmArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rpmArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_rpm = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_rpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpm, 0);
    lv_obj_set_y(ui_rpm, 150);
    lv_obj_set_align(ui_rpm, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_rpm, "7777");
    lv_obj_set_style_text_color(ui_rpm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpm, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_rpm, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_rpm, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_rpm, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_rpm, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_color(ui_rpm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_rpm, 255, LV_PART_MAIN | LV_STATE_USER_3);

}
