// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Dash V2

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 160);
    lv_obj_set_height(ui_Container2, 240);
    lv_obj_set_x(ui_Container2, 160);
    lv_obj_set_y(ui_Container2, 0);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coolantRed = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_coolantRed);
    lv_obj_set_width(ui_coolantRed, 160);
    lv_obj_set_height(ui_coolantRed, 85);
    lv_obj_clear_flag(ui_coolantRed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_coolantRed, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_coolantRed, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_oilRed = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_oilRed);
    lv_obj_set_width(ui_oilRed, 160);
    lv_obj_set_height(ui_oilRed, 75);
    lv_obj_set_x(ui_oilRed, 0);
    lv_obj_set_y(ui_oilRed, 80);
    lv_obj_clear_flag(ui_oilRed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_oilRed, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_oilRed, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_intakeRed = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_intakeRed);
    lv_obj_set_width(ui_intakeRed, 240);
    lv_obj_set_height(ui_intakeRed, 110);
    lv_obj_set_x(ui_intakeRed, 0);
    lv_obj_set_y(ui_intakeRed, 170);
    lv_obj_clear_flag(ui_intakeRed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_intakeRed, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_intakeRed, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_coolantLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_coolantLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_coolantLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_coolantLabel, 20);
    lv_obj_set_y(ui_coolantLabel, 20);
    lv_label_set_text(ui_coolantLabel, "Coolant temp:");
    lv_obj_set_style_text_color(ui_coolantLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_coolantLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_coolantLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_coolantLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_coolantLabel, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_coolantTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_coolantTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_coolantTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_coolantTemp, 20);
    lv_obj_set_y(ui_coolantTemp, 35);
    lv_label_set_text(ui_coolantTemp, "120 °C");
    lv_obj_set_style_text_color(ui_coolantTemp, lv_color_hex(0x00F7FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_coolantTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_coolantTemp, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_coolantTemp, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_coolantTemp, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_coolantTemp, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_coolantTemp, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_color(ui_coolantTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_coolantTemp, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_oilLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_oilLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oilLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_oilLabel, 20);
    lv_obj_set_y(ui_oilLabel, 90);
    lv_label_set_text(ui_oilLabel, "Oil temp:");
    lv_obj_set_style_text_color(ui_oilLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oilLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oilLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_oilLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_oilLabel, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_oilTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_oilTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oilTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_oilTemp, 20);
    lv_obj_set_y(ui_oilTemp, 105);
    lv_label_set_text(ui_oilTemp, "80");
    lv_obj_set_style_text_color(ui_oilTemp, lv_color_hex(0x00F7FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oilTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oilTemp, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_oilTemp, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_oilTemp, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_color(ui_oilTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_oilTemp, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_intakeLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_intakeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_intakeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_intakeLabel, 20);
    lv_obj_set_y(ui_intakeLabel, 160);
    lv_label_set_text(ui_intakeLabel, "Intake temp:");
    lv_obj_set_style_text_color(ui_intakeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_intakeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_intakeLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_intakeLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_intakeLabel, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_intakeTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_intakeTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_intakeTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_intakeTemp, 20);
    lv_obj_set_y(ui_intakeTemp, 175);
    lv_label_set_text(ui_intakeTemp, "80");
    lv_obj_set_style_text_color(ui_intakeTemp, lv_color_hex(0x00F7FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_intakeTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_intakeTemp, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_intakeTemp, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_intakeTemp, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_color(ui_intakeTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_intakeTemp, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_rpmLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_rpmLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmLabel, 190);
    lv_obj_set_y(ui_rpmLabel, 40);
    lv_label_set_text(ui_rpmLabel, "RPM:");
    lv_obj_set_style_text_color(ui_rpmLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpmLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpmLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_rpmLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_rpmLabel, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_rpm = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_rpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpm, 190);
    lv_obj_set_y(ui_rpm, 70);
    lv_label_set_text(ui_rpm, "7777");
    lv_obj_set_style_text_color(ui_rpm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpm, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_rpm, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_rpm, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_rpm, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_rpm, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_color(ui_rpm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_rpm, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_boostBar = lv_bar_create(ui_Screen1);
    lv_bar_set_range(ui_boostBar, 0, 1500);
    lv_bar_set_value(ui_boostBar, 200, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_boostBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_boostBar, 160);
    lv_obj_set_height(ui_boostBar, 40);
    lv_obj_set_x(ui_boostBar, 160);
    lv_obj_set_y(ui_boostBar, 200);
    lv_obj_set_style_radius(ui_boostBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_boostBar, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_boostBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_boostBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_boostBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_boostBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_boost = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_boost, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_boost, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_boost, 190);
    lv_obj_set_y(ui_boost, 150);
    lv_label_set_text(ui_boost, "0.4");
    lv_obj_set_style_text_color(ui_boost, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_boost, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_boost, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_boost, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_boost, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_boost, lv_color_hex(0xEEFF00), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_boost, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_color(ui_boost, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_boost, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_boostLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_boostLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_boostLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_boostLabel, 190);
    lv_obj_set_y(ui_boostLabel, 120);
    lv_label_set_text(ui_boostLabel, "Boost:");
    lv_obj_set_style_text_color(ui_boostLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_boostLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_boostLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_boostLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_text_opa(ui_boostLabel, 255, LV_PART_MAIN | LV_STATE_USER_3);

}
