// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Dash V1

#ifndef _DASH_V1_UI_H
#define _DASH_V1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void arcAnim_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_coolantRed;
extern lv_obj_t * ui_oilRed;
extern lv_obj_t * ui_intakeRed;
extern lv_obj_t * ui_coolantLabel;
extern lv_obj_t * ui_coolantTemp;
extern lv_obj_t * ui_oilLabel;
extern lv_obj_t * ui_oilTemp;
extern lv_obj_t * ui_intakeLabel;
extern lv_obj_t * ui_intakeTemp;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_boostBar;
extern lv_obj_t * ui_boostLabel;
extern lv_obj_t * ui_boost;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_rpmLabel;
extern lv_obj_t * ui_rpmArc;
extern lv_obj_t * ui_rpm;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_accelX;
extern lv_obj_t * ui_accelY;
extern lv_obj_t * ui_circle1;
extern lv_obj_t * ui_accelPointer;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_gearBackground;
extern lv_obj_t * ui_gearDisp;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_Signal_200_bold);
LV_FONT_DECLARE(ui_font_Signal_30_Normal);
LV_FONT_DECLARE(ui_font_Signal_70_bold);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
